import './globals.css';
import { DM_Sans, Open_Sans } from 'next/font/google';

import DirectAccess from '@/app/Components/DirectAccess/DirectAccess';
import Image from 'next/image';
import GoogleAnalytics from '@/app/Components/GoogleAnalitycs/GoogleAnalitycs';
import GoogleTagManagerHead from '@/app/Components/GoogleAnalitycs/GoogleTagManagerHead';
import GoogleTagManagerBody from '@/app/Components/GoogleAnalitycs/GoogleTagManagerBody';
import { BsWhatsapp } from 'react-icons/bs';
export const metadata = {
  title: 'SocialMedia1989',
  description: 'Generated by create next app',
};
//Windows10
const openSans = Open_Sans({
  subsets: ['cyrillic', 'latin'],
  weight: ['300', '400'],
});
//Windows98
const dmSans = DM_Sans({
  subsets: ['latin', 'latin-ext'],
  weight: ['400', '500', '700'],
});
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <GoogleTagManagerHead
          GTM_CONTAINER_ID={process?.env?.GTM_CONTAINER_ID || ''}
        />
      </head>

      <GoogleTagManagerBody
        GTM_CONTAINER_ID={process?.env?.GTM_CONTAINER_ID || ''}
      />
      <GoogleAnalytics GA_TRACKING_ID={process?.env?.GA_TRACKING_ID || ''} />

      <body
        className={`grid-body-wrapper max-w-screen max-h-screen overflow-hidden font-w98 `}
      >
        <header className="flex min-h-sreen items-start justify-start icons-area p-4">
          <nav className="flex flex-wrap gap-4 fixed bottom-0 left-0  sm:flex-col sm:static w-screen md:w-full">
            <DirectAccess route="/clients" name="Clientes" />

            <DirectAccess route="/about" name="Nosotros" />

            <DirectAccess
              id={'contact_form_id'}
              icon={'/ico/w98/ico/mailbox_world.ico'}
              route="/contact"
              name="Contactanos"
            />
            <DirectAccess
              icon={'/ico/w98/ico/help_book_big.ico'}
              route="/courses"
              name="Nuestros Cursos"
            />
          </nav>
        </header>
        {/* Windows 10 bg */}
        <Image
          className="-z-10 object-cover"
          fill
          alt="background image"
          priority
          src={'/images/w95F.jpg'}
        />
        {children}
        <a
          href="https://wa.me/5491127951972"
          target="_blank"
          className="absolute cursor-pointer hover:bg-green-700 duration-150 flex justify-center items-center z-[5000] right-4 bottom-6 p-3 bg-green-600 rounded-full shadow-md shadow-neutral-600 text-neutral-100"
        >
          <BsWhatsapp className="text-3xl" />
        </a>
      </body>
    </html>
  );
}
